### ISSUE TITLE
스터디클럽 관련 조회 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [Hi9hFive5/esc#6]
## 설명
> 기능 설명
- 회원별 자신이 리더인 스터디클럽 목록 조회
- 스터디클럽 상세 조회
<br>

## 진행 사항
- [x] 리더인 스터디클럽 목록 조회
- [x] 상세 조회
<br>

## 기타 사항
스터디클럽 페이지 모든 사람들 볼 수 있도록 전체 목록 생성 필요?

**Comment by dongh810** [comment]
음 다른사람들이 모든 스터디클럽을 볼 필요는 없을거 같습니다!!!!!!!!
